{"name": "test_comparewithCC", "status": "failed", "statusDetails": {"message": "AssertionError: cc and zz comparison failed\nassert 45 == 35", "trace": "supply_AA_BB_CC = [25, 35, 45]\n\n    def test_comparewithCC(supply_AA_BB_CC):\n    \tzz=35\n>   \tassert supply_AA_BB_CC[2]==zz,\"cc and zz comparison failed\"\nE    AssertionError: cc and zz comparison failed\nE    assert 45 == 35\n\nPyTest\\test_basic_fixture.py:15: AssertionError"}, "start": 1623009173834, "stop": 1623009173834, "uuid": "0d10fbec-7037-4db1-bbfc-d7447a19acf4", "historyId": "bf35e9374cbdcd4c8638fadc51f598dd", "testCaseId": "440fcc5b0205b33736d9f21043e951e8", "fullName": "PyTest.test_basic_fixture#test_comparewithCC", "labels": [{"name": "parentSuite", "value": "PyTest"}, {"name": "suite", "value": "test_basic_fixture"}, {"name": "host", "value": "Sanjay-PC"}, {"name": "thread", "value": "3224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PyTest.test_basic_fixture"}]}