{"name": "test_comparewithBB_file2", "status": "failed", "statusDetails": {"message": "AssertionError: bb and zz comparison failed\nassert 35 == 25", "trace": "supply_AA_BB_CC = [25, 35, 45]\n\n    def test_comparewithBB_file2(supply_AA_BB_CC):\n    \tzz=25\n>   \tassert supply_AA_BB_CC[1]==zz,\"bb and zz comparison failed\"\nE    AssertionError: bb and zz comparison failed\nE    assert 35 == 25\n\nPyTest\\test_basic_fixture2.py:8: AssertionError"}, "start": 1623009347393, "stop": 1623009347393, "uuid": "aa1f316a-0ac0-499a-9c2f-c21784e6fa2d", "historyId": "96231593d5feb3b23286bb28aa391cbd", "testCaseId": "dfcbe1c6642419f0dd1b06be608572d4", "fullName": "PyTest.test_basic_fixture2#test_comparewithBB_file2", "labels": [{"name": "parentSuite", "value": "PyTest"}, {"name": "suite", "value": "test_basic_fixture2"}, {"name": "host", "value": "Sanjay-PC"}, {"name": "thread", "value": "108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PyTest.test_basic_fixture2"}]}